server:
  port: 8000
spring:
  datasource:
    username: root
    password: abc123
    url: jdbc:mysql://127.0.0.1:3306/link
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 2000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl