server:
  port: 8002
spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
      # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml

  data:
    redis:
      database: 0
      port: 6379
      host: 127.0.0.1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
short-link:
  domain:
    default: http://nurl.ink:8002
  goto-domain:
    white-list:
      enable: false
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
  stats:
    locale:
      amap-key: ccac52b42db08d7a8f993fca8af058da